### ISSUE TITLE
geolite.maxmind.com down?

### ISSUE THREAD

**Issue by jim256** [stephenlb/geo-ip#1]
Just tried running the container and got:

```
The command '/bin/sh -c curl -O http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz' returned a non-zero code: 6
curl: (6) Could not resolve host: geolite.maxmind.com
```

Couldn't hit that URL myself either. No longer valid?

**Comment by stephenlb** [comment]
Good find.  Yes that URL has changed.

**Comment by stephenlb** [comment]
https://dev.maxmind.com/geoip/geoip2/geolite2/ - they changed their policy.  Lets see if there is an approach here.

**Comment by stephenlb** [comment]
Okay fixed.  09d7fd1bf9f3432b429b3302861f62d5bbd522ed

Run to update your local:

```shell
git pull origin master
docker build -t geo-ip .
docker run -e IPRANGE='54.0.0.0/30' geo-ip               ## a few IPs
```
